### ISSUE TITLE
config for smtp -> fixes validation for bluesky admin email

### ISSUE THREAD

**Issue by alexgustafson** [davepeck/bluesky-pds-docker#1]
I added this to the dokku config setup. Emails with validation codes are now sent.

PDS_EMAIL_SMTP_URL=smtp://[user]:[password]@[smtp.url.com]:[port]"
PDS_EMAIL_FROM_ADDRESS=admin@mydomain.com

replace values with whatever smtp provider and account you are using.

Thanks for this project!

**Comment by davepeck** [comment]
Thank you! Will update my notes and the README.

**Comment by davepeck** [comment]
@alexgustafson README is updated as are my blog notes -- thank you! It should have occurred to me that validation emails would be sent via the PDS too.
